# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linearCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_linearCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

quadraticCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_quadraticCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

cubicCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_cubicCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

qrootCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_qrootCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

exponentialCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_exponentialCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

logECpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_logECpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

sigmoidCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_sigmoidCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

stepCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_stepCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

spikeCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_spikeCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

sinLowCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_sinLowCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

sinHighCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_sinHighCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

linearPeriodicCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_linearPeriodicCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

varyingFreqCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_varyingFreqCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

circleCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_circleCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

xShapedCpp <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_xShapedCpp', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

