# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call('nlf_rcpparma_hello_world', PACKAGE = 'nlf')
}

rcpparma_outerproduct <- function(x) {
    .Call('nlf_rcpparma_outerproduct', PACKAGE = 'nlf', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('nlf_rcpparma_innerproduct', PACKAGE = 'nlf', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('nlf_rcpparma_bothproducts', PACKAGE = 'nlf', x)
}

linear <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_linear', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

quadratic <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_quadratic', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

cubic <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_cubic', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

qroot <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_qroot', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

exponential2 <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_exponential2', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

logE <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_logE', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

sigmoid <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_sigmoid', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

step <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_step', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

spike <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_spike', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

sinLow <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_sinLow', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

sinHigh <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_sinHigh', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

linearPeriodic <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_linearPeriodic', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

varyingFreq <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_varyingFreq', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

circle <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_circle', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

xShaped <- function(x, noise, noiseLevel, numNoise, n) {
    .Call('nlf_xShaped', PACKAGE = 'nlf', x, noise, noiseLevel, numNoise, n)
}

